name: mongo36-configurable
version: '1.5'
base: core20
summary: MongoDB document-oriented database
description: |
    The Snap configuration files are stored in: /var/snap/mongo36-configurable/common/mongodb.conf 
   
    the snaps mantains data and configuration across installations
    
    use "mongo36-configurable.reset" to reset data and configuration    
    use "mongo36-configurable.restore-conf" to reset configuration
    use "mongo36-configurable.remove-data" to reset data 
    
    restart the app fater any procedure above    
    
    MongoDB is a high-performance, open source, schema-free
    document-oriented data store that's easy to deploy, manage
    and use. It's network accessible, written in C++ and offers 
    the following features.

       * Collection oriented storage - easy storage of object-style data
       * Full index support, including on inner objects
       * Query profiling
       * Replication and fail-over support
       * Efficient storage of binary data including large objects (e.g. videos)
       * Auto-sharding for cloud-level scalability

    High performance, scalability, and reasonable depth of functionality
    are the goals for the project.

confinement: strict

apps:
    
    mongod:
        command: bin/run.sh 
        daemon: simple
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
        restart-condition: on-failure
        
        
    restore-conf: 
        command: bin/restorec.sh
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

        
    remove-data: 
        command: bin/remdata.sh
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
        
        
    reset: 
        command: bin/reset.sh
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
        
    info:
        command: bin/info.sh 
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
       

parts:
    mongodb:
        plugin: nil
        stage-packages:
            - mongodb-server
            - mongodb-server-core
            - libssl-dev
            - libcurl-dev
   
    shscripts:  
        source: ./shscripts/
        plugin: dump
        organize:
          '*': bin/
