name: mongo36-configurable
version: 0.1
base: core18
summary: MongoDB document-oriented database

description: |
    MongoDB is a high-performance, open source, schema-free
    document-oriented data store that's easy to deploy, manage
    and use. It's network accessible, written in C++ and offers
    the following features:

       * Collection oriented storage - easy storage of object-style data
       * Full index support, including on inner objects
       * Query profiling
       * Replication and fail-over support
       * Efficient storage of binary data including large objects (e.g. videos)
       * Auto-sharding for cloud-level scalability

    High performance, scalability, and reasonable depth of functionality
    are the goals for the project.

confinement: strict

apps:
    
    mongod:
        command: bin/run.sh 
        daemon: simple
        plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]
        restart-condition: on-failure

        


plugs:
    home:
    network:
    network-bind:

parts:
    mongodb:
        plugin: nil
        stage-packages:
            - mongodb
            - libssl1.1
            - libcurl3

  
    shscripts:  
        source: ./shscripts/
        plugin: dump
        organize:
          '*': bin/
